factorial
js-tasks-ru/jsbasic-20220901_a-semenovyh pull request #3
Opened 2022-09-08 17:16 UTC by AlexSem82

2022-09-09 10:11 UTC, SinimaWath commented
у тебя есть конфликт в первой задаче.

Сделай:
- `git pull upstream master`

 - Пофикси конфликт, убери в файлике разделители `=====` `<===` и т,д
 
 - Сделай коммит и запушь
 
 
 Вот тут хороший пример: https://www.youtube.com/watch?v=PXK1hIifpWU

2022-09-09 10:12 UTC, SinimaWath requested changes

2022-09-09 10:12 UTC, SinimaWath commented on 1-module/1-task/index.js
> +let n;
`n` - у тебя аргумент функции, так что не нужно обьявлять вне функции

2022-09-09 14:13 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-09 14:13 UTC, AlexSem82 commented on 1-module/1-task/index.js
> +let n;
Да, спасибо. Убрал.

2022-09-09 14:15 UTC, AlexSem82 commented
> у тебя есть конфликт в первой задаче.
> 
> Сделай:
> 
> * `git pull upstream master`
> * Пофикси конфликт, убери в файлике разделители `=====` `<===` и т,д
> * Сделай коммит и запушь
> 
> Вот тут хороший пример: https://www.youtube.com/watch?v=PXK1hIifpWU

не понял, о каких разделителях речь?

2022-09-10 12:43 UTC, SinimaWath approved these changes

2022-09-10 12:43 UTC, merged